import SwiftUI
struct MoreView:View {var body:some View {List {NavigationLink("Wilderness Mode") {WildernessView()};NavigationLink("Known Beacons") {BeaconsView()};NavigationLink("Receiver Devices") {ReceiversView()};NavigationLink("Saved Hunts") {SessionsView()};NavigationLink("Signal History") {HistoryView()};NavigationLink("Frequency Bookmarks") {BookmarksView()};NavigationLink("Diagnostics") {DiagnosticsView()};NavigationLink("Settings & Privacy") {SettingsView()};NavigationLink("Field Safety") {SafetyView()}}.navigationTitle("Field tools")}}
struct HistoryView:View {@EnvironmentObject var field:FieldModel;var body:some View {List {ForEach(field.state.sessions.reversed()) {s in NavigationLink {SessionDetailView(id:s.id)} label:{VStack(alignment:.leading){Text(s.name);Text("\(s.measurements.count) power samples · \(s.startedAt.formatted())").font(.caption).foregroundStyle(.secondary)}}}}.navigationTitle("Signal History")}}
struct ReceiversView:View {
    @EnvironmentObject var field: FieldModel
    @State private var name = ""
    @State private var id = ""
    @State private var url = ""
    @State private var token = ""
    @State private var target = ""
    var body:some View {List {Section("iPhone BLE") {Text(field.ble.status);Text("Capabilities: BLE advertisements and RSSI. Battery and antenna bearing are not supplied by normal advertisements.").font(.caption);Button("Scan") {field.ble.start()}};ForEach(field.receivers,id:\.id) {r in Section(r.name) {Text(r.status);Text(r.endpoint.absoluteString).font(.caption);Text("Capabilities: \(r.capabilities.joined(separator:", "))").font(.caption);Text("Rate \(String(format:"%.1f",r.sampleRate)) samples/s · Round-trip \(r.latencyMilliseconds.map {"\(Int($0)) ms"} ?? "unavailable")").font(.caption);Text("Latest \(r.latest?.formatted() ?? "not received") · Battery \(r.batteryPercent.map {"\(Int($0))%"} ?? "not supplied")").font(.caption);Button(r.isConnected ? "Disconnect" : "Connect") {if r.isConnected{r.stop()}else{r.start()}};Button("Use for hunt") {field.receiverID=r.id};Button("Remove receiver",role:.destructive) {field.removeReceiver(r.id)}}};Section("Add receiver bridge") {TextField("Receiver ID (matches packet receiverId)",text:$id);TextField("Name",text:$name);TextField("https://bridge.example",text:$url).keyboardType(.URL).textInputAutocapitalization(.never);SecureField("Bridge access token",text:$token);Button("Connect authorized receiver") {field.connectReceiver(id:id,name:name,url:url,token:token);token=""};Text("HTTPS certificate trust must be configured on the iPhone for a private bridge. No security bypass is included.").font(.caption)};Section("Hunt an external target") {Text("Selected receiver: \(field.receiverID)").font(.caption);TextField("Target signalIdentifier",text:$target);Button("Start authorized RF hunt") {field.startHunt(target:target,name:target,source:field.receiverID)}}}.navigationTitle("Receivers")}
}
struct DiagnosticsView:View {
    @EnvironmentObject var field:FieldModel
    var body:some View {List {LabeledContent("GPS",value:field.location.status);LabeledContent("Heading",value:field.location.freshHeading.map {"\(Int($0))°"} ?? "Unavailable");LabeledContent("BLE",value:field.ble.status);LabeledContent("Receiver",value:field.receiverID);LabeledContent("Samples",value:"\(field.selectedMeasurements.count)");LabeledContent("Location accuracy",value:field.location.latest.map {"±\(Int($0.horizontalAccuracy)) m"} ?? "Unavailable");let values=field.selectedMeasurements;LabeledContent("Average sample interval",value:values.count>1 ? String(format:"%.2f s",values.last!.timestamp.timeIntervalSince(values.first!.timestamp)/Double(values.count-1)) : "Unavailable");LabeledContent("RSSI variance",value:field.currentRegion.map {String(format:"%.2f",$0.variance)} ?? "Unavailable");LabeledContent("Estimator",value:"WeightedRegionEstimator/v1");Text("Confidence is heuristic and uncalibrated. No position is verified by this estimator.").font(.caption);LabeledContent("Storage",value:field.isSaving ? "Writing locally" : "Local");LabeledContent("Outbox",value:"\(field.state.outbox.count)");LabeledContent("Network",value:field.connectivity.status)}.navigationTitle("Diagnostics")}
}
