import SwiftUI
import UniformTypeIdentifiers
import SignalTrackerCore
struct SessionsView:View {
    @EnvironmentObject var field:FieldModel;@State private var importing=false
    var body:some View {List {ForEach(field.state.sessions.reversed()) {s in NavigationLink {SessionDetailView(id:s.id)} label:{VStack(alignment:.leading,spacing:5) {Text(s.name).font(.headline);ProvenanceBadge(simulated:s.isSimulated);Text("\(s.startedAt.formatted()) · \(s.measurements.count) samples").font(.caption).foregroundStyle(.secondary)}}.swipeActions {Button("Delete",role:.destructive) {field.deleteSession(s.id)}}};if field.state.sessions.isEmpty {Text("No saved recordings yet.").foregroundStyle(.secondary)};Button("Import session JSON") {importing=true}}.navigationTitle("Saved sessions").fileImporter(isPresented:$importing,allowedContentTypes:[.json]) {r in switch r {case .success(let url):field.importSession(url:url);case .failure(let e):field.message=e.localizedDescription}}}
}
struct SessionDetailView:View {
    @EnvironmentObject var field:FieldModel;let id:UUID;@State private var replay=1.0;@State private var shareURL:URL?;@State private var notes=""
    var body:some View {ScrollView {if let s=field.state.sessions.first(where:{$0.id==id}) {VStack(alignment:.leading,spacing:16) {ProvenanceBadge(simulated:s.isSimulated);Text(s.name).font(.title2);Text("\(s.measurements.count) measurements · \(s.spectrum.count) spectrum frames");Text("Replay position").font(.caption);Slider(value:$replay,in:0.02...1);CoordinateRouteView(session:replaySession(s),opacity:0.5);Button("Select this recording") {guard field.activeID==nil else{field.message="Stop the active hunt before opening a recording.";return};field.selectedID=s.id;field.receiverID=s.measurements.first?.receiverID ?? "iphone-ble";field.tab=1};TextField("Session notes",text:$notes,axis:.vertical).onAppear {notes=s.notes};Button("Save notes") {field.saveNotes(notes,for:id)};HStack {ForEach(["json","csv","geojson"],id:\.self) {format in Button("Export \(format.uppercased())") {do{shareURL=try field.exportSession(s,format:format)}catch{field.message=error.localizedDescription}}}};if let url=shareURL {ShareLink(item:url,label:{Label("Share export",systemImage:"square.and.arrow.up")})}}.padding()}}.background(InstrumentTheme.background).navigationTitle("Recording")}
    private func replaySession(_ s:SignalSession)->SignalSession {var copy=s;copy.measurements=Array(s.measurements.prefix(max(1,Int(Double(s.measurements.count)*replay))));let date=copy.measurements.last?.timestamp ?? s.route.prefix(max(1,Int(Double(s.route.count)*replay))).last?.timestamp ?? s.startedAt;copy.route=s.route.filter {$0.timestamp<=date};copy.estimatedRegions=s.estimatedRegions.filter {$0.createdAt<=date};return copy}
}
