import SwiftUI
import SignalTrackerCore
struct WildernessView:View {
    @EnvironmentObject var field:FieldModel
    @State private var waypoint=""
    var body:some View {ScrollView {VStack(alignment:.leading,spacing:16) {
        FieldCard(title:"Offline navigation") {Text(field.location.status).font(.headline);if let p=field.location.latest {Text(String(format:"%.5f, %.5f",p.latitude,p.longitude)).font(.title3.monospaced());Text("GPS ±\(Int(p.horizontalAccuracy)) m");Text(p.altitude.map {"Altitude \(Int($0)) m"} ?? "Altitude unavailable")};Text("Compass \(field.location.freshHeading.map {"\(Int($0))°"} ?? "unavailable")");Button("Enable foreground GPS") {field.location.start(mode:field.state.settings.batteryMode)}.buttonStyle(.bordered)}
        if field.activeID==nil {Button("Mark this as my starting point") {field.startWilderness()}.buttonStyle(.borderedProminent)}
        if let s=field.selected {FieldCard(title:"Your route") {HStack {Metric(label:"Walked",value:String(format:"%.0f",Geo.routeDistance(s.route)),unit:"m");Spacer();Metric(label:"Elapsed",value:String(format:"%.0f",(s.endedAt ?? Date()).timeIntervalSince(s.startedAt)/60),unit:"min")};NavigationLink("Return to start") {ReturnToStartView()};TextField("Waypoint name",text:$waypoint);Button("Save waypoint") {field.markWaypoint(name:waypoint);waypoint=""};ForEach(s.waypoints) {w in Text("◆ \(w.name) · \(String(format:"%.5f, %.5f",w.latitude,w.longitude))").font(.caption)};if let last=s.lastServicePoint {Text("Last connectivity observed here: \(String(format:"%.5f, %.5f",last.latitude,last.longitude))").font(.caption).foregroundStyle(.blue)};if field.activeID != nil {Button("Stop & save",role:.destructive) {field.stop()}}}}
        NavigationLink("Wilderness safety & emergency information") {SafetyView()}
    }.padding()}.background(InstrumentTheme.background).navigationTitle("Wilderness")}
}
struct ReturnToStartView:View {
    @EnvironmentObject var field:FieldModel
    var body:some View {ScrollView {VStack(spacing:18) {if let s=field.selected,let start=s.route.first {FieldCard(title:"Return to start") {if let current=field.location.freshFix {let bearing=Geo.bearing(current,start.fix);Text("\(Geo.compass(bearing)) · \(Int(bearing))°").font(.largeTitle.monospaced());Metric(label:"Straight-line distance",value:String(format:"%.0f",Geo.distance(current,start.fix)),unit:"m")} else {Text("A fresh GPS fix is required for a current return bearing.");Button("Acquire GPS") {field.location.start(mode:field.state.settings.batteryMode)}};Text("Walked route: \(Int(Geo.routeDistance(s.route))) m");Text("Compass: \(field.location.freshHeading.map {"\(Int($0))°"} ?? "unavailable")");Text("The straight line may cross impassable terrain. Follow your breadcrumb route and assess conditions.").font(.caption).foregroundStyle(.secondary)};CoordinateRouteView(session:s,opacity:0.4)}else{EmptyField(title:"No starting point",detail:"Begin a wilderness session with a fresh GPS fix.",icon:"flag")}}.padding()}.background(InstrumentTheme.background).navigationTitle("Return to start")}
}
struct SafetyView:View {
    var body:some View {List {Section("Navigation") {Text("Carry an independent map and compass, tell someone your plan, and monitor battery. Signal hunting is not your sole emergency-navigation method.");Text("GPS accuracy varies. Trees, hills, buildings and reflections can attenuate signals or create false peaks. Strong power does not guarantee a nearby source.");Text("Estimated regions and last-connectivity points are observations, never emergency guarantees.")};Section("Emergency information") {Text("If in immediate danger, use your iPhone's Emergency SOS or call the appropriate local emergency number when available. Availability depends on location, device and connectivity.");Text("This app does not contact emergency services or transmit your location automatically.");Text("Keep warmth, water, shelter and an independent means of navigation available.")}}.navigationTitle("Field safety")}
}
